server:
  port: 8081

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  level:
    toy.ojm: DEBUG
    org.springframework.web: DEBUG
  config: classpath:log/logback-local.xml

kakao:
  appKey: ${KAKAO_REST_API_KEY}
---

spring:
  config:
    activate:
      on-profile: local-mysql-sun

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${database.name}
    username: ${database.username}
    password: ${database.password}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: local-mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopl?useSSL=false&allowPublicKeyRetrieval=true&verifyServerCertificate=false&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    username: root
    password: 1234qwer
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: local-h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: live

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${database.url}/${database.name}
    username: ${database.username}
    password: ${database.password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: false

logging:
  level:
    toy.ojm: INFO
    org.springframework.web: INFO
  config: classpath:log/logback-live.xml
