server:
  port: 8081

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

logging:
  level:
    toy.ojm: DEBUG
    org.springframework.web: DEBUG

---

spring:
  config:
    activate:
      on-profile: local-mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopl?useSSL=false&allowPublicKeyRetrieval=true&verifyServerCertificate=false&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    username: root
    password: 1234qwer
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: local-h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: local-mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql.real.datasource.url}
    username: ${mysql.real.datasource.username}
    password: ${mysql.real.datasource.password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    toy.ojm: DEBUG
    org.springframework.web: DEBUG

