server:
  port: 8081

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
#      add-mappings: false

#logging:
#  config: classpath:log/logback-local.xml
#  level:
#    root: DEBUG

kakao:
  appKey: ${KAKAO_REST_API_KEY:defaultDummyValue}
---
spring:
  config:
    activate:
      on-profile: local-real
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${database.name}
    username: ${database.username}
    password:
      ${database.password}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---

spring:
  config:
    activate:
      on-profile: local-mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopl?useSSL=false&allowPublicKeyRetrieval=true&verifyServerCertificate=false&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    username: root
    password: 1234qwer
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
---

spring:
  config:
    activate:
      on-profile: local-h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false

logging:
  level:
    org.hibernate.SQL: INFO

---

spring:
  config:
    activate:
      on-profile: live

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${database.url}/${database.name}
    username: ${database.username}
    password: ${database.password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: false
logging:
  config: classpath:log/logback-live.xml
